<Project>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Optimize>true</Optimize>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcInstructionSet>x86-64</IlcInstructionSet>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <StripSymbols>true</StripSymbols>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <TieredPGO>false</TieredPGO>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <UseSharedCompilation>false</UseSharedCompilation>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Deterministic>true</Deterministic>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Shared/CSharp/Benchmark.cs" Link="Benchmark.cs" />
  </ItemGroup>
</Project>

